version: '2'

services:
  php:
    build: ./build/
    volumes:
      - ./:/code/
    working_dir: /code/
    env_file: .env
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    volumes:
      - db:/var/lib/mysql/
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
    ports:
      - "3306:3306"

volumes:
  db:
    driver: "local"
